site_name: DeviceConnect Users
theme: 'readthedocs'
remote_branch: 'master'
site_url: https://deviceconnectusers.github.io
google_analytics: ['UA-79831666-1', 'deviceconnectusers.github.io']
extra_css: []
extra_javascript: []
pages:
- 'Top': 'index.md'
- 'DeviceConnectについて': 'about.md'
- 'デモサイトの使い方': 'demosite.md'
- '→ デモサイトはこちら': 'toManager.md'
- 'Android':
  - 'はじめてみよう': 'android.md'
  - 'オフラインでの利用': 'android/offline.md'
  - '外部ブラウザからの利用': 'android/external.md'
  - 'DeviceConnectManagerについて': 'android/device_connect_manager.md'
  - 'プラグインをビルドする': 'android/plugin.md'
  - 'Pebbleプラグイン': 'android/plugins/pebble.md'
- iOS:
  - 'はじめてみよう（iOS）': 'ios.md'
  - 'DeviceConnect Browserをビルドする': 'ios/browser.md'
  - '外部ブラウザから使う': 'ios/external.md'
- 'JavaScript':
  - 'はじめてみよう（JavaScript）': 'javascript.md'
  - 'DeviceConnectアプリケーションの作り方': 'javascript/basic.md'
  - 'JavaScript SDKをPromiseベースにする': 'javascript/app.md'
- 'Web API':
  - 'Web APIについて': 'webapi.md'
  - '認証API': 'webapi/authorization.md'
  - '死活確認API': 'webapi/availabillity.md'
  - 'バッテリーAPI': 'webapi/battery.md'
  - 'コネクトAPI': 'webapi/connect.md'
  - 'Canvas API': 'webapi/canvas.md'
  - 'デバイス向き/加速度API': 'webapi/deviceorientation.md'
  - 'ファイル参照API': 'webapi/fileDescriptor.md'
  - 'ファイルAPI': 'webapi/file.md'
  - '認可API': 'webapi/grant.md'
  - '湿度API': 'webapi/humidity.md'
  - '照度 API': 'webapi/illuminance.md'
  - 'キーイベントAPI': 'webapi/keyevent.md'
  - 'ライトAPI': 'webapi/light.md'
  - 'メディアプレイヤーAPI': 'webapi/mediaPlayer.md'
  - 'メディアストリーミング録画API': 'webapi/mediastreamRecording.md'
  - '通知API': 'webapi/notification.md'
  - '電話API': 'webapi/phone.md'
  - '電力メーターAPI': 'webapi/powermeter.md'
  - '近接センサーAPI': 'webapi/proximity.md'
  - 'リモートコントローラーAPI': 'webapi/remoteController.md'
  - 'サービス検索API': 'webapi/servicediscovery.md'
  - 'サービス情報API': 'webapi/serviceinformation.md'
  - 'デバイス設定API': 'webapi/settings.md'
  - '温度 API': 'webapi/temperature.md'
  - 'タッチAPI': 'webapi/touch.md'
  - 'バイブレーションAPI': 'webapi/vibration.md'
  - 'スコープについて': 'webapi/scope.md'
  - 'エラーについて': 'webapi/error.md'
- 'WebSocket':
  - 'WebSocketについて': 'websocket.md'
  - 'バッテリーAPI': 'websocket/battery.md'
  - 'コネクトAPI': 'websocket/connect.md'
  - 'デバイス向き/加速度API': 'websocket/deviceorientation.md'
  - 'ファイル参照API': 'websocket/fileDescriptor.md'
  - 'キーイベントAPI': 'websocket/keyevent.md'
  - '電話API': 'websocket/phone.md'
  - '近接センサーAPI': 'websocket/proximity.md'
  - 'タッチAPI': 'websocket/touch.md'
- '対応デバイス':
  - '対応デバイスについて': 'devices.md'
  - 'MOVERIO': 'devices/moverio.md'
  - 'THETA m15': 'devices/theta_m15.md'
  - 'THETA S': 'devices/theta_s.md'
  - 'Color 1000': 'devices/color_1000.md'
  - 'F-PLUG': 'devices/f_plug.md'
  - 'Chromecast': 'devices/chromecast.md'
  - 'Android': 'devices/android.md'
- '利点&欠点': 'pros-cons.md'

